name: Test
on:
  - push:
      branches:
        - main
  - workflow-dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tastinggrounds/.github/.workflows/create-release.yaml@main