name: create-release
description: Tag and create a release in GitHub
runs:
  using: 'composite'
  steps:
    - name: PWD
      shell: bash
      run: |
        if test -f "package.json"; then
          VERSION=v$(cat package.json | jq .version -r)
        elif test -f "VERSION"; then
          VERSION=v$(cat VERSION)
        else
          echo "No package.json or VERSION file found"
          exit 1
        fi

        gh --version
        
    