name: create-release
description: Tag and create a release in GitHub
inputs:
  require_main_branch:
    description: 'Require the action to run on the main branch'
    type: 'boolean'
    required: false
    default: true
runs:
  using: 'composite'
  steps:
    - name: Check Branch
      if: ${{ inputs.require_main_branch }}
      shell: bash
      run: |
        if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
          echo "This action can only run on the main branch. Current branch is ${{ github.ref }}"
          exit 1
        fi
    - name: Tag and Create Release
      shell: bash
      run: |
        git fetch --tags

        if test -f "package.json"; then
          VERSION=v$(cat package.json | jq .version -r)
        elif test -f "VERSION"; then
          VERSION=v$(cat VERSION)
        else
          echo "No package.json or VERSION file found"
          exit 1
        fi

        EXIT_CODE=0

        echo "Found Version: $VERSION"

        if [ $(git tag -l "$VERSION") ]; then
          echo "Skip release $VERSION because it already exists."	
          exit 0
        else	
          git push origin $VERSION	
          echo "Tagged $VERSION"	
        fi
        
        echo "Creating GitHub Release: $VERSION"

        if test -f "CHANGELOG.md"; then
          RELEASE_LINE_NUM=$(grep -n "\[$VERSION\]" CHANGELOG.md | cut -d : -f 1)
          CHANGELOG_START=$(($RELEASE_LINE_NUM + 1))

          mkdir -p /tmp/ghr
          sed -n "$CHANGELOG_START,/^$/p" CHANGELOG.md > /tmp/ghr/release-notes.md

          LINK=$(gh release create $VERSION --notes-file /tmp/ghr/release-notes.md --title $VERSION)
        else
          LINK=$(gh release create $VERSION --notes "No Release Notes" --title $VERSION)
        fi

        echo "Created Release: $VERSION"
        echo $LINK

        rm -rf /tmp/ghr

        exit 0
    