name: create-release
description: Tag and create a release in GitHub
runs:
  using: 'composite'
  steps:
    - name: PWD
      shell: bash
      run: |
        if test -f "package.json"; then
          VERSION=v$(cat package.json | jq .version -r)
        elif test -f "VERSION"; then
          VERSION=v$(cat VERSION)
        else
          echo "No package.json or VERSION file found"
          exit 1
        fi

        gh --version

        EXIT_CODE=0	

        git tag ${VERSION} || EXIT_CODE=$?	

        if [ $EXIT_CODE -ne 0 ];	
        then	
          echo "Skip taging $VERSION because it already exists."	
          exit 0
        else	
          git push origin $VERSION	
          echo "Tagged $VERSION"	
        fi
        
        echo "Creating GitHub Release: $VERSION"

        if test -f "CHANGELOG.md"; then
          RELEASE_LINE_NUM=$(grep -n "\[$VERSION\]" CHANGELOG.md | cut -d : -f 1)
          CHANGELOG_START=$(($RELEASE_LINE_NUM + 1))

          mkdir -p /tmp/ghr
          sed -n "$CHANGELOG_START,/^$/p" CHANGELOG.md > /tmp/ghr/release-notes.md

          LINK=$(gh release create $VERSION --notes-file /tmp/ghr/release-notes.md --title $VERSION)
        else
          echo "HEYO"
          LINK=$(gh release create $VERSION --notes "No Release Notes" --title $VERSION)
        fi

        echo "Created Release: $VERSION"
        echo $LINK

        rm -rf /tmp/ghr

        exit 0
    