name: Tag and Create Release
description: Tag and create a release in GitHub
runs:
  using: 'composite'
  steps:
    - name: Tag Git Version
      shell: bash
      run: ./scripts/release.sh
        
    